version: '3.8'

services:
  message-correction-api:
    build: .
    ports:
      - "8000:80"    # Internal container port 80, exposed as 8000 for debugging
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2.7
    container_name: caddy_server
    ports:
      - "80:80"      # HTTP port
      - "443:443"    # HTTPS port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - message-correction-api
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
